### ISSUE TITLE
No connection to apt.syncthing.net possible

### ISSUE THREAD

**Issue by mtelgkamp** [syncthing/apt-web#31] opened 2023-10-10 08:30 UTC
Currently, it seems to not possible to connect to https://apt.syncthing.net/. There is an SSL error shown:
`PR_END_OF_FILE_ERROR` in Firefox
`ERR_EMPTY_RESPONSE` in Chromium

Also, when connecting with `apt update`, it says `Could not handshake`.

The [Qualys SSL Check](https://www.ssllabs.com/ssltest/analyze.html?d=apt.syncthing.net&hideResults=on) says `No secure protocols supported`

**Comment by er-pa** [comment] 2023-10-10 08:40
The hosting provider where the apt-server is deployed has some issues on their Kubernetes cluster;
https://github.com/syncthing/syncthing/issues/9160#issuecomment-1754500757

**Comment by bt90** [comment] 2023-10-10 08:44
Duplicate of #9160

**Closed** 2023-10-10 08:44 UTC
